MIA-170,168,251,263, and 249
GSA/made-in-america-data pull request #61
Opened 2022-02-25 17:52 UTC by kennethedwards-bixal

Ticket attempts to close above referenced tickets that will
-remove waiver
-include eslint/prettier
-update node version to 16
-remove ENOME error in pipeline
-script will return non zero code
-include unit test

TEST: checkout stage branch, pull down, and run `node buildwaiverdata.js`

2022-02-25 20:29 UTC, scottqueen-bixal commented
work should be merged into `develop` first, https://github.com/GSA/made-in-america-data/blob/develop/CONTRIBUTING.md#branches

otherwise `develop` will be out of sync which could break others' work who are following the contribution guidelines

2022-02-25 20:35 UTC, kennethedwards-bixal commented
It was merged into develop first.
- I made branch called hotfix/nodeversion, then merged that into develop.
Christian approved it and then merged it into stage.
- then I merged your edits into stage.
Now I'm ready to merge into main.

On Fri, Feb 25, 2022 at 3:29 PM Scott Queen ***@***.***>
wrote:

> work should be merged into develop first,
> https://github.com/GSA/made-in-america-data/blob/develop/CONTRIBUTING.md#branches
>
> otherwise develop will be out of sync which could break others' work who
> are following the contribution guidelines
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/GSA/made-in-america-data/pull/61#issuecomment-1051233601>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AV6WRNKPFQLVFHRLUAGJCA3U47RCPANCNFSM5PK4R4PQ>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-03-01 14:26 UTC, jefffortune requested changes
There are two conflicts
- waivers-data.json
- waivers.csv
Can you please fix these conflicts, thank you.

2022-03-01 14:26 UTC, jefffortune commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
JSON doesn't allow inline comments.

2022-03-01 14:42 UTC, kennethedwards-bixal commented on .vscode/launch.json
> +    // Use IntelliSense to learn about possible attributes.
Conflicts resolved

2022-03-01 15:43 UTC, merged