[MIA-277] Make changes to public data script to pull Urgent Waiver data
GSA/made-in-america-data pull request #90
Opened 2022-04-04 18:56 UTC by kennethedwards-bixal

Refactored Notes: 
1.  I created a new file called `CompileUrgentWaiver.js` that will be responsible for running the script for the urgent waivers. In the this and file `CompileJsonApp.js` I refactored the code to  pass in files, keys, and URLs so we can reuse the functions in the Datascript instead of having to re-write a whole new DataScript file just for urgent waivers. 

2.  I created a new file called under the `StringReplace` folder called `urgent-index.js`. This file will parse the urgent waiver forms data to a user friendly format.  I did it this way because if it ran under the `index.js` file used for nonavailability, the data would append properties to the urgent waiver that are not needed such as ombDeterimation, requestStatus, and waiverCoverage to name a few. Such properties would all return `N/A`. 

To differentiate the two types of files, I created an if statement on line 134 in DataScript/index.js. This if statement looks for the property wavierType(something that Nonavailability waivers don't have) and points those files to the `urgent-index.js` which manipulates urgent waiver strings. I think this works well because if ever need new urgent waiver specific properties, we can just add them to this file. I worked with Stephanie to double check public data fields.

3. I wrote a new set of tests. I copied the bulk of the `compileJsonApp.spec.js` format. I made sure that the proper urgent waivers _ids were present but more importantly I made sure that waivers were NOT removed during the script as the remove function is part of the overall processData function. Additionally, string manipulation was also tested. 

To Test: 
 - comment out line 18 in `CompileJSonApp.js` and comment out line 22 in `CompileUrgentWaiver.js`
- `npm run test`

Important note in this PR: the URL for urgent waiver is in the portal-test and not real future data.

2022-04-06 11:18 UTC, jefffortune requested changes

2022-04-06 11:18 UTC, jefffortune commented on src/Utility/StringReplace/urgent-index.js
> +/**
You can add uncertain, Uncertain to the  StringReplace/index.js switch statement to reduce overall code.

2022-04-06 11:18 UTC, jefffortune commented on test/CompileUrgentWaiver.js.spec.js
> +// eslint-disable-next-line node/no-unpublished-require
Can combine these to CompileJSONAppTest, it testing the same things. Remove this file will help with DRY

2022-04-06 11:18 UTC, jefffortune commented on CompileUrgentWaiver.js
> +if (process.env.NODE_ENV !== 'production') {
Combine this with the cCompieJsonApp.js file. This way circle CI doesnt have to change.

2022-04-11 14:13 UTC, kennethedwards-bixal commented
Made changes, ran tests programmatically and visually checked as well.

2022-04-19 16:05 UTC, closed without merging